language: php

sudo: false

git:
    depth: 1

php:
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache

script:
    - composer install
    - ./vendor/bin/phpunit

after_script:
    ## Scrutinizer
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar --access-token="86bd9078d28a29fca0a80e4998931db4abb845fe3b681dfd099a9dddd0f8bd71" code-coverage:upload --format=php-clover ./build/logs/clover.xml
