language: php

sudo: required

services:
    - docker

git:
    depth: 1

php:
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install

before_script:
    - docker-compose -f tests/Functional/docker-compose.yml up -d --scale kong=2
    - sleep 20 # give postgresql the time to start

script:
    - ./vendor/bin/phpunit

after_script:
    ## Scrutinizer
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar --access-token="86bd9078d28a29fca0a80e4998931db4abb845fe3b681dfd099a9dddd0f8bd71" code-coverage:upload --format=php-clover ./build/logs/clover.xml
    ## Sami
    - wget http://get.sensiolabs.org/sami.phar
    - php sami.phar update .sami.php

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: eu-west-2
    bucket: unikorp-docs
    local_dir: build/api
    upload-dir: kong-admin-api/master
    skip_cleanup: true
