language: php

sudo: required

services:
    - docker

git:
    depth: 1

php:
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install

before_script:
    - docker-compose -f tests/Functional/docker-compose.yml up -d --scale kong=2
    - sleep 5 # give postgresql some time to be ready before kong migration
    - docker run --rm --env "KONG_DATABASE=postgres" --env "KONG_PG_HOST=functional_db_1" --link "functional_db_1" --network "functional_default" kong:0.11 kong migrations up &>/dev/null
    - sleep 15 # give kong containers some time to join the cluster

script:
    - ./vendor/bin/phpunit

before_deploy:
    ## Sami
    - wget http://get.sensiolabs.org/sami.phar
    - php sami.phar update .sami.php

deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      region: eu-west-2
      bucket: docs.unikorp.io
      local_dir: build/api
      upload-dir: kong-admin-api/api/master
      skip_cleanup: true
      on:
        branch: master
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      region: eu-west-2
      bucket: docs.unikorp.io
      local_dir: build/api
      upload-dir: kong-admin-api/api/$TRAVIS_TAG
      skip_cleanup: true
      on:
        tags: true

after_script:
    ## Scrutinizer
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar --access-token="86bd9078d28a29fca0a80e4998931db4abb845fe3b681dfd099a9dddd0f8bd71" code-coverage:upload --format=php-clover ./build/logs/clover.xml
